---
name: "Java CI with Gradle"
"on":
  push:
    branches:
      - "main"
permissions:
  contents: "read"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
      - name: "Set up JDK 21"
        uses: "actions/setup-java@v5"
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "gradle validation"
        uses: "gradle/actions/wrapper-validation@v5"
      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v5"
      - name: "Run the tests"
        run: "./gradlew test"
      - name: "Run build"
        run: "./gradlew bootJar"
      - name: "Save result jar for further use"
        uses: "actions/upload-artifact@v5"
        with:
          name: "app.jar"
          path: "build/libs/*"
          retention-days: 5
