---
name: "Automatic Rebase"
"on":
  push:
    branches:
      - "main"
permissions:
  contents: "write"
jobs:
  rebase:
    name: "Rebase `dependencies` with `main`"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
          ref: "dependencies"
      - run:
          "git config user.name github-actions\ngit config user.email github-actions@github.com\n\
          git rebase origin/main\ngit push origin dependencies --force\n"
